---
title: "Homework 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Please do the homework as posted weekly! Only the ICAs will be formally assessed and officially recorded; thus you do not need to hand in HW (except the ICAs) for the purposes of grading.



# By [UCL week](https://www.ucl.ac.uk/estates/sites/estates/files/ucl_academic_calendar_2023_2024.pdf)

* [ICA1 2023](https://tsoo-math.github.io/ucl4/2023-ica1-stat9-release.html)
* [ICA2 2023](https://tsoo-math.github.io/ucl4/2023-ica2-project.html)
* [ICA3 2023](https://tsoo-math.github.io/ucl4/2023-ica3-stat9-release.html)

## Tenative schedule, may be updated


* Week 6 (2 Oct - 8 Oct):  
  - [Getting started with R](https://tsoo-math.github.io/ucl2/hello-R-2001.html)
  - [Getting started with Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/hello-p.ipynb/%3Fflush_cache%3Dtrue)
  - [Exercises](https://tsoo-math.github.io/ucl2/2021-HW-week6.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW1-sol.html)
      - [Solutions in Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week6.ipynb/%3Fflush_cache%3Dtrue)
* Week 7 (9 Oct - 15 Oct): 
  - [Exercises](https://tsoo-math.github.io/ucl2/2021-HW-week7.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW2-sol.html)
      - [Solutions in Python, including the last Q](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week7.ipynb/%3Fflush_cache%3Dtrue)
* Week 8 (16 Oct - 22 Oct):  
  - [Exercises](https://tsoo-math.github.io/ucl2/2021-HW-week8.html)
    - [Solutions in R](https://tsoo-math.github.io/ucl/QHW3-sols.html)
    - [Solutions in Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week8.ipynb/%3Fflush_cache%3Dtrue)
* Week 9 (23 Oct - 29 Oct):  
  - [Exercises](https://tsoo-math.github.io/ucl/QHW4.html)
    - [Solutions in R](https://tsoo-math.github.io/ucl/QHW4-sol.html)
    - [Solutions in Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week9.ipynb)
* Week 10 (30 Oct - 5 Nov):   
  * [ICA1 2023](https://tsoo-math.github.io/ucl4/2023-ica1-stat9-release.html)
  - [Continuous-time MC exercises](https://tsoo-math.github.io/ucl/QHW5.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW5-sols.html)
      - [Solutions in Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week10.ipynb)
  - [ICA1 2022](https://tsoo-math.github.io/ucl3/2022-ica1-stat9-release.html) 
    * [ICA1 2022-sols](https://tsoo-math.github.io/ucl3/2022-ica1-stat9.html)
        * [ICA1-sols 2021](https://tsoo-math.github.io/ucl2/2021-ica1-stat9.html)
* Week 11 (6 Nov - 12 Nov):  Reading break
* Week 12 (13 Nov - 19 Nov): ICA1 due
  - [Exercises](https://tsoo-math.github.io/ucl/QHW6.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW6-sols.html)
* Week 13 (20 Nov - 26 Nov):  
  - [Exercises](https://tsoo-math.github.io/ucl/QHW6.1.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW6.1-sols.html)
* Week 14 (27 Nov - 3 Dec):  
  - [Exercises](https://tsoo-math.github.io/ucl/QHW7.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW7-sols.html)
  
* Week 15 (4 Dec - 10 Dec): 
  - [Exercises](https://tsoo-math.github.io/ucl/QHW8.1.html)
    - [Solutions in R](https://tsoo-math.github.io/ucl/QHW8.1-sols.html)
  * [ICA2 2023 project ideas](https://tsoo-math.github.io/ucl4/2023-ica2-project.html)
  
* week 16 (11 Dec - 15 Dec):
  * Revisions:  
  * [ICA3 2023](https://tsoo-math.github.io/ucl4/2023-ica3-stat9-release.html)
    * [ICA3 2021](https://tsoo-math.github.io/ucl2/2021-ica3-stat9-release.html)
      * [sols](https://tsoo-math.github.io/ucl3/2021-ica3-stat9.html)
  


# Other notes


* [ICA1](https://tsoo-math.github.io/ucl4/2023-ica1-stat9-release.html): Released 03/11/2023; Due 17/11/2023
* [ICA2](https://tsoo-math.github.io/ucl4/2023-ica2-project.html): Released 4/12/2023;  Due 01/03/2024
* [ICA3](https://tsoo-math.github.io/ucl4/2023-ica3-stat9-release.html): Released 15/12/2023; Due 09/02/2024


<br>
<br>

 Version:  `r format(Sys.time(), '%d %B %Y')`

<br>
<br>
<br>