---
title: "Live/In-person session diary 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# General information

We may  *attempt* to live stream, the live in-person sessions.  Please note that it is UCL's expectation that students attend in-person.  The Zoom link is available [here](https://ucl.zoom.us/my/terrysoo).  Not all sessions will be recorded or streamed.  The recording links will be available on Moodle.


# By [UCL week](https://www.ucl.ac.uk/estates/sites/estates/files/ucl_academic_calendar_2023_2024.pdf)


# Week 6
  * First meeting: introductions, module outline and mechanics
  * We discussed the basics of rejection sampling
  * We proved the weak law of large numbers and discussed various forms of convergence
  * This meeting was recorded can the link to access this is available only on Moodle

# Week 7
  * We discussed the homework from last week and introduced the concept of coupling.
  * [Worksheet](https://tsoo-math.github.io/ucl4/week7-2023-inclass.html)
    * [Partial Solutions](https://tsoo-math.github.io/ucl3/week7-2022-inclass-sols.html)

# Week 8

* We discussed the relation between uniform random variables, coin flips, and the inverse transform method.
* We discussed coupling in more detail and its relation with the total variational distance.
* We introduced Markov chains, and the key assumption of them being aperiodic and irreducible

* [Worksheet](https://tsoo-math.github.io/ucl4/week8-2023-inclass.html)
  * [Partial solutions](https://tsoo-math.github.io/ucl4/week8-2023-inclass-sol.html)

# Week 9
* We discussed Poisson processes
  * [Shiny App](https://terry-soo.shinyapps.io/Poisson-disc/)
    * [Source](https://tsoo-math.github.io/ucl/app.R)
* [Worksheet](https://tsoo-math.github.io/ucl4/week9-2023-inclass.html)
  * [Solutions](https://tsoo-math.github.io/ucl4/week9-2023-inclass-sols.html)

# Week 10

* We discussed ICA1 expectations and guidelines.
  * We went over [ICA1 2022](https://tsoo-math.github.io/ucl3/2022-ica1-stat9.html)
* We discussed and coded a simple voting model.  More in-depth information and background can be found [here](https://www.math.uvic.ca/~aquas/papers/paper23.pdf) or [here](https://www.worldscientific.com/doi/10.1142/S0219493704000912).
  * [Worksheet](https://tsoo-math.github.io/ucl4/week10-2023-inclass.html) and [solutions](https://tsoo-math.github.io/ucl4/week10-2023-inclass-sols.html) 

# Week 11

* we discussed the content delivery and ethos of the module.
* We reviewed continuous-time Markov chains.

* [Worksheet](https://tsoo-math.github.io/ucl4/week11-2023-inclass.html)
  * [Solutions](https://tsoo-math.github.io/ucl4/week11-2023-inclass-sols.html)


# Week 12

* We discussed expectations for ICA1
* We reviewed the worksheets on MCMC and Voroni cells
* We introduced a renewal-type argument for Markov chains


# Week 13

* We reviewed convolutions and introduced some ideas in renewal theory, including Excessive life and stationary increments
* [Worksheet](https://tsoo-math.github.io/ucl4/week12-2023-inclass.html)

# Week 14

* We discussed the two versions of Little's theorem.
* [Worksheet](https://tsoo-math.github.io/ucl4/week14-2023-inclass.html)


# Other notes



* ICA1: Released 03/11/2023; Due 17/11/2023
* ICA2: Released 08/12/2023; Due 01/03/2024
* ICA3: Released 15/12/2022; Due 09/02/2024




<br>
<br>

 Version:  `r format(Sys.time(), '%d %B %Y')`

<br>
<br>
<br>