---
title: "Live/In-person session diary 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# General information

We may  *attempt* to live stream, the live in-person sessions.  Please note that it is UCL's expectation that students attend in-person.  The Zoom link is available [here](https://ucl.zoom.us/my/terrysoo).  Not all sessions will be recorded or streamed. 


# By [UCL week](https://www.ucl.ac.uk/staff/sites/staff/files/cal_2022_2023.pdf)

* Week 6 (3 Oct - 9 Oct):  
  - Introductions, first meeting.
  - Introduction to R, Python
  - Uniform random variables and generating random variables
  - (Weak) law of large numbers
  - This meeting was recorded, and is available via Moodle (only)
  
* Week 7 (10 Oct - 16 Oct): 
  - We discussed rejection sampling and introduced the concept of coupling. 
  - Random triangles [worksheet](https://tsoo-math.github.io/ucl3/week7-2022-inclass.html)
    - [solutions](https://tsoo-math.github.io/ucl3/week7-2022-inclass-sols.html)
 
 
* Week 8 (17 Oct - 23 Oct):  
  - We discussed the homework; in particular, random walks on graphs and reversibility.
  - Playing with a two-by-two Markov chain and symbolic computing in Python 
    - [worksheet](https://tsoo-math.github.io/ucl3/week8-2022-inclass.html)
      - [solutions](https://tsoo-math.github.io/ucl3/week8-2022-inclass-sols.html)
    - This meeting was recorded, and is available via Moodle (only)
  
* Week 9 (24 Oct - 30 Oct): 
  - We discussed how Doeblin's coulping was the basis of our convergence theorems for Markov chains, and we also introduced Poisson point processes on finite volumes.
  - Playing with data from a Markov chain
    - [worksheet](https://tsoo-math.github.io/ucl3/week9-2022-inclass.html)
      - [solutions](https://tsoo-math.github.io/ucl3/week9-2022-inclass-sols.html)
  - [Shiny app for Poisson on a disc](https://terry-soo.shinyapps.io/Poisson-disc/)
    - [Source](https://tsoo-math.github.io/ucl/app.R)
  - [Poisson and WW2](https://rss.onlinelibrary.wiley.com/doi/pdf/10.1111/j.1740-9713.2019.01315.x)
  - [Animal versus human poll, what Americans think](https://today.yougov.com/topics/society/articles-reports/2021/05/13/lions-and-tigers-and-bears-what-animal-would-win-f)
  - This meeting was recorded, and is available via Moodle (only)
* Week 10 (31 Oct - 6 Nov): 
  - We discussed the expectations for ICA1, and the module in general.  We also went over a homework exercise on the uniform distribution, and introduced continuous Markov chains, using [holding](https://finalfantasy.fandom.com/wiki/Doom_(status)) times.
  - [Reinforced random walk](https://tsoo-math.github.io/ucl3/week10-2022-inclass.html) (non-Markovian processes)
    - [solutions](https://tsoo-math.github.io/ucl3/week10-2022-inclass-sols.html)
    - [optional materials to help understand trapping](https://tsoo-math.github.io/ucl/borel.html)
    - [optional materials to help understand simple random walk](https://www.dropbox.com/s/m6ei3u8uh8t5vur/exercise-sheet.pdf?dl=0)
 
* Week 11 (7 Nov - 13 Nov):  Reading break
  
* Week 12 (14 Nov - 20 Nov): 
  - We discussed the inspection paradox in the context of Poisson processes
  - We discussed the renewal theory and the strong Markov property in the context of Markov chains
  - [worksheet](https://tsoo-math.github.io/ucl3/week12-2022-inclass.html)
    - [solutions](https://tsoo-math.github.io/ucl3/week12-2022-inclass-sols.html)
  - This meeting was recorded, and is available via Moodle (only)
* Week 13 (21 Nov - 27 Nov): 
  - We discussed the excessive time distribution and its connection to stationary increments.
  - We discussed how the Blackwell renewal theorem hold of Poisson processes, and how it is *easier* for renewal proceses with stationary increments:
      - We argued that in the stationary case, we have $m(t+h) - m(t) = \mathbb{E}N(h) = m(h)$; I tried to make an argument that $\mathbb{E}N(h) = h/\mu$ just using the fact that $\lim_{h \to \infty}m(t)/t = 1/\mu$, which is **not** correct; a more involved argument is given in the notes.
  - [worksheet](https://tsoo-math.github.io/ucl3/week13-2022-inclass.html)
  - This meeting was recorded, and is available via Moodle (only)
* Week 14 (28 Nov - 4 Dec):  
  
* Week 15 (5 Dec - 11 Dec): 
 
* week 16 (12 Dec - 16 Dec):
 


# Other notes

* First term (Monday 26 September 2022 -- Friday 16 December 2022)

* week 12: (14 Nov - 20 Nov; 2022):  ICA1 due, 18 November
* week 24: (6 Feb - 12 Feb;  2023):  ICA3 due, 9 February
* week 27: (27 Feb - 5 Mar; 2023):  ICA2 due, 3 March


<br>
<br>

 Version:  `r format(Sys.time(), '%d %B %Y')`

<br>
<br>
<br>