---
title: "Session diary 2026"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# General information

We may  *attempt* to live stream, the live in-person sessions.  Please note that it is UCL's expectation that students attend in-person.  The Zoom link is available [here](https://ucl.zoom.us/my/terrysoo).  Not all sessions will be recorded or streamed.  The recording [link](https://moodle.ucl.ac.uk/mod/url/view.php?id=9436609) is password protected, with the password available on Moodle.


# [Homework](https://tsoo-math.github.io/ucl7/hw-stat41.html)

# By [UCL week](https://www.ucl.ac.uk/srs/sites/srs/files/ucl_calendar_2026_27v2.pdf)


# Week 6

- Read the first two chapters of the notes

## Week 6a

- We introduced divide-and-conquer type arguments
 - Binary search
 - A version of the King's salary [see Peter Winkler's book, page 18](https://math.dartmouth.edu/news-resources/electronic/puzzlebook/book/book.pdf)

- We introduced a version of [selection sort](https://en.wikipedia.org/wiki/Selection_sort)





##  Week 6b

- We introduced faster than $O(n^2)$ multiplication, where $n=2^k$ is the number of digits,  due to [Karatsuba ](https://en.wikipedia.org/wikiiKaratsuba_algorithm); we got $O(n^{\log_2 3})$; this is $3^k$, which  corresponds to the number of single digit multiplications at the end of the divide and conquer.
  -  Although the final answer is correct, in my haste, I think I did not properly estimate the number of additions/subtractions required.     I should of said that each level $j$, we basically have $3^j$ additions with numbers that  which are of length $2^{k-j}$, this gives the summation,
  $$\sum_{j=1}^k 2^{k-j}3^j \leq 3\cdot3^{k}.$$
- We formally introduced the big $O$ notation and gave a sufficient condition in terms of limits
- We analysed more carefully the selection sort algorithm.
  - We introduced the concept of a loop-invariant
  - We wrote some R code for this sorting algorithm 




<br>
<br>

 Version:  `r format(Sys.time(), '%d %B %Y')`

<br>
<br>
<br>