---
title: "Live/In-person session diary 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# General information

We may  *attempt* to live stream, the live in-person sessions.  Please note that it is UCL's expectation that students attend in-person.  The Zoom link is available [here](https://ucl.zoom.us/my/terrysoo).  Not all sessions will be recorded or streamed.  The recording links will be available on Moodle.


# By [UCL week](https://www.ucl.ac.uk/srs/sites/srs/files/ucl_calendar_2024_25_1.pdf)


# Week 6

* We discussed the basic module mechanics and lecture-workshop style.
* We discussed the following [problem](https://arxiv.org/abs/2409.00732) that was on [Twitter](https://x.com/littmath/status/1769044719034647001)--due to Daniel Litt.
* We discussed the law of large numbers and its role in simulations.

# Week 7

* We reviewed Monte Carlo integration
* We reviewed sample spaces and uniform random variables
* We discussed von Neumann's rejection sampling
* We introduced coupling.  [Bond percolation](https://mathworld.wolfram.com/BondPercolation.html) was used to demonstrate the usefulness of coupling.  We mentioned the following related optional topics.
  * [Bunkbed conjecture is false](https://en.wikipedia.org/wiki/Bunkbed_conjecture)
  * [Couplas and wall street](https://www.pure.ed.ac.uk/ws/files/15459604/Formula_final2.pdf)

# Week 8

* We reviewed and introduced Markov chains and some proof techniques with the worksheet.  We also discussed Doeblin's coupling and its role in proving convergence.  We also briefly mentioned an alternative approach based in linear algebra:  [Perron–Frobenius theorem](https://doi.org/10.1080/00029890.2021.1944755).


* [Worksheet](https://tsoo-math.github.io/ucl5/week8-2024-inclass.html)

  * [Partial sols](https://tsoo-math.github.io/ucl4/week8-2023-inclass-sol.html)

# Week 9

* We introduced Poisson processes and discussed the Metropolis algorithm.

* [See Q1](https://tsoo-math.github.io/ucl2/2021-ica3-stat9-release.html)  
* [Worksheet](https://tsoo-math.github.io/ucl4/week11-2023-inclass.html)
  * [Parital solutions](https://tsoo-math.github.io/ucl4/week11-2023-inclass-sols.html)



# Week 10

* We discussed the procedures for ICA1 and went over some of the questions from [ICA1-2023](https://tsoo-math.github.io/ucl4/2023-ica1-stat9-release.html).
 
 
# Week 12

* We briefly discussed continuous-time Markov chains.  We went over in some detail, the renewal-type argument for the a version of LLN for Markov chains.

* [Worksheet](https://tsoo-math.github.io/ucl5/week12-2024-inclass.html)
  * [Partial solutions](https://tsoo-math.github.io/ucl5/week12-2024-inclass-Sols.html)


# Week 13

* We discussed how to recover stationary increments in the context of renewal processes.

* [Worksheet](https://tsoo-math.github.io/ucl5/week13-2024-inclass.html)
 

# Week 14

* [Worksheet](https://tsoo-math.github.io/ucl5/week14-2024-inclass.html)
 

# Other notes


<br>
<br>

 Version:  `r format(Sys.time(), '%d %B %Y')`

<br>
<br>
<br>