---
title: Stochastic systems course schedule and diary
author: Terry Soo
date:  Fall 2020
output: html_document
---



# By UCL week

* Week 4 (21 Sept - 27 Sept):  First email
* Week 5 (28 Sept - 4 Oct):
* Week 6 (5 Oct - 11 Oct):  Introductions:  Introduction to R and Law of Large Numbers and R
* Week 7 (12 Oct - 18 Oct): Random variables: theory and practice, Coupling and total variational distance, Review of Markov chains
* Week 8 (19 Oct - 25 Oct):  Making Markov chains converge
* Week 9 (26 Oct - 1 Nov):  Coupling from the past, Poisson processes
* Week 10 (2 Nov - 8 Nov):  Continuous-time Markov chains; ICA 1 assigned   
* Week 11 (9 Nov - 15 Nov):  Reading break
* Week 12 (16 Nov - 22 Nov): Introduction to renewal theory; ICA 1 due 
* Week 13 (23 Nov - 29 Nov):  Introduction to queuing theory
* Week 14 (30 Nov - 6 Dec):  
  + Introduction to queuing theory II 
  + Return of the law of large numbers
  + ICA 2 (projects chosen and assigned)
* Week 15 (7 Dec - 13 Dec):
  + Introduction to the probabilistic method and random graphs
  +  ICA 3 assigned
* week 16 (14 Dec - 20 Dec):
  + Introduction to Python (Please continue to do all your submitted work in R)

* week 23: (2021):  [ICA 3](https://tsoo-math.github.io/ucl/ica3-stat9-release.html) due; 3 February 2021, 13:00 London time
* we3k 27: (2021):  [ICA 2](https://tsoo-math.github.io/ucl/ICAproject-ideas.html) due; 3 March 2021, 13:00 London time

# Other notes

* First term Monday (28 September 2020 -- Friday 18 December 2020)



<br>
<br>

# Version:  `r format(Sys.time(), '%d %B %Y')`

<br>
<br>
<br>
