---
title: Stochastic systems live sesssion diary
author: Terry Soo
date:  Fall 2020
output: html_document
---

#  Abstract

* We will meet for a live session once a week in the slot Monday 2-4 PM that would have been normally our lecture time.   
* We may not use all two hours.    
* These live sessions will not be lectures, but rather a combination of office hours, tutorials, and workshops.   
* The pre-recorded lectures are meant to replace the lectures that *would* have took place at this time.   
*  These sessions are meant to reinforce and supplement the material covered in the pre-recorded lectures. 
* In order to encourage everyone to speak freely and interact, we will *not* usually be recording these sessions.
* These live sessions will be conducted over Zoom. 




# By UCL week


* Week 6 (5 Oct - 11 Oct): 

    + [First meeting Monday 2PM UK time](https://ucl.zoom.us/j/5904204711)
    + [Exercise sheet](https://tsoo-math.github.io/ucl/class1.html)
    +  [Solutions](https://tsoo-math.github.io/ucl/class1sol.html)
    +  We discussed some module logistics.  We went into breakout rooms to do the exercises, and returned to the main Zoom room to briefly discuss the solutions.  This meeting was not recorded.   
* Week 7 (12 Oct - 18 Oct):
    +  [Second meeting Monday 2PM UK time](https://ucl.zoom.us/j/5904204711)
    +  [R exercise sheet: gambler's ruin](https://tsoo-math.github.io/ucl/gambler.html)
    +  [Solutions](https://tsoo-math.github.io/ucl/gambler-sol.html)
    +  We discussed more about the logisitics of of the module and went over the first homework.  Afterwards, we went into breakout rooms to work on the R exercises; we returned to the main room to discuss solutions.  This meeting was not recorded.
* Week 8 (19 Oct - 25 Oct):
    +  [Third meeting Monday 2PM UK time](https://ucl.zoom.us/j/5904204711)
    +  [R exercise sheet: transition matrices](https://tsoo-math.github.io/ucl/class3.html)
    +  We discussed the [solutions to HW2](https://tsoo-math.github.io/ucl/QHW2-sol.html).  Then we went into breakout rooms to work on the R exercise sheet; we returned to the main room to briefly discuss the  R exercise sheet.  This meeting was not recorded.
* Week 9 (26 Oct - 1 Nov):
    +  [Fourth meeting Monday 2PM UK time](https://ucl.zoom.us/j/5904204711)
    +  We discussed the [solutions to HW3](https://tsoo-math.github.io/ucl/QHW3-sol.html), maths, stats, code, and typesetting.  We also discussed the Doeblin coupling.  This meeting was not recorded.
* Week 10 (2 Nov - 8 Nov):   
    +  [Fifth meeting Monday 2PM UK time](https://ucl.zoom.us/j/5904204711)
    +  We discussed the [solutions to HW4](https://tsoo-math.github.io/ucl/QHW4-sol.html).   
    +  We discussed the ICA; in particular,  plagiarism and collusion, and R Markdown coding and typesetting expectations.    This meeting was not recorded.
    
* Week 11 (9 Nov - 15 Nov):  [Reading break](https://www.youtube.com/watch?v=kI6MWZrl8v8)


* Week 12 (16 Nov - 22 Nov): 
    +  [Sxith meeting Monday 2PM UK time](https://ucl.zoom.us/j/5904204711)
    +  [Exercise sheet](https://tsoo-math.github.io/ucl/class6.html)

* Week 13 (23 Nov - 29 Nov):
* Week 14 (30 Nov - 6 Dec): 
* Week 15 (7 Dec - 13 Dec):
* week 16 (14 Dec - 20 Dec):


<br>
<br>

# Version: `r format(Sys.time(), '%d %B %Y')`

<br>
<br>
<br>
