---
title: A subset of links for Stat 0009
author: 
date:  Fall 2020
output: html_document
---

# Abstract

These are a subset of the links that are available on the main Moodle page for our module.   This is *not* meant to be a replacement for [Moodle](https://moodle.ucl.ac.uk/), but may be useful if you are having trouble accessing Moodle.   In addition, most of html files were generated in R Markdown, and if you are interested in the source file, you can probably access it by changing the extension to *Rmd*.


# General links

* [Module Outline](https://tsoo-math.github.io/ucl/link0009.html)

* [Schedule](https://tsoo-math.github.io/ucl/0009diary.html)

* [Live session information](https://tsoo-math.github.io/ucl/live.html)

* [Homework](https://tsoo-math.github.io/ucl/homework.html)

* [Recorded Lectures on Youtube](https://tsoo-math.github.io/ucl/videosyoutube0009.html)

#  Lecture notes



* [Introduction to R](https://tsoo-math.github.io/ucl/intro-R.html)      [(pdf)](https://tsoo-math.github.io/ucl/intro-R.pdf)

* [Law of Large numbers and R](https://tsoo-math.github.io/ucl/prob-viaR.html)   [(pdf)](https://tsoo-math.github.io/ucl/prob-viaR.pdf)


* [How reliable are simulations](https://tsoo-math.github.io/ucl/random2d.html)

*  [Random variables: theory and practice](https://tsoo-math.github.io/ucl/randomTP-slides.html)  [(pdf)](https://tsoo-math.github.io/ucl/randomTP.pdf)

* [Coupling and total variational distance](https://tsoo-math.github.io/ucl/TV.html)

*  [You always knew coupling](https://tsoo-math.github.io/ucl/coupling-rev.html)




*  [Brief review of MC](https://tsoo-math.github.io/ucl/reviewMC.html)


*  [Making MC converge](https://tsoo-math.github.io/ucl/markov-c.html)


*  [Coupling from the past](https://tsoo-math.github.io/ucl/coupling-from-past.html)


*  [Poisson processes](https://tsoo-math.github.io/ucl/poisson.html)


*  [Poisson processes, worked out exercises](https://tsoo-math.github.io/ucl/poisson-ex.worked.html)


*  [Continuous-time Markov chains](https://tsoo-math.github.io/ucl/continuous-timeMC.html)



*  [Introduction to renewal theory I](https://tsoo-math.github.io/ucl/intro-renewal.html)

*  [Introduction to renewal theory II](https://tsoo-math.github.io/ucl/intro-renewaltwo.html)

*  [Introduction to renewal theory III](https://tsoo-math.github.io/ucl/intro-renewalthree.html)



*  [Introduction to queueing theory](https://tsoo-math.github.io/ucl/intro-queues.html)

*  [Introduction to queueing theory II](https://tsoo-math.github.io/ucl/intro-queuestwo.html)

*   [The return of the law of large numbers](https://tsoo-math.github.io/ucl/borel.html)


*   [Introduction to the probabilistic method](https://tsoo-math.github.io/ucl/randomone.html)

*   [Introduction to random graphs](https://tsoo-math.github.io/ucl/randomtwo.html)

*   [Introduction to maths/stats with Python](https://tsoo-math.github.io/ucl/first.html)

*   [Shiny App](https://terry-soo.shinyapps.io/Poisson-disc/)

*   [Shiny App Source](https://tsoo-math.github.io/ucl/app.R)


<br>
<br>

Version: `r format(Sys.time(), '%d %B %Y')`


<br>
<br>
<br>
