---
title: "Homework 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Please do the homework as posted weekly! Only the ICAs will be formally assessed and officially recorded; thus you do not need to hand in HW (except the ICAs) for the purposes of grading.



# By [UCL week](https://www.ucl.ac.uk/srs/sites/srs/files/ucl_calendar_2025_26v1.pdf)

* [ICA1:](https://tsoo-math.github.io/ucl6/2025-ica1-stat9-release.html) Released 31 Oct 2025; Due 14 Nov 2025
* ICA2: Released 5 Dec 2025; Due 6 March 2026
* ICA3: Released 12 Dec 2025; Due 6 Feb 2026



## Tenative schedule, may be updated


* Week 6 (29 Sept - 5 Oct):  
  - [Getting started with R](https://tsoo-math.github.io/ucl2/hello-R-2025.html)
  - [Getting started with Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/hello-p-2025.ipynb/%3Fflush_cache%3Dtrue)
  - [Exercises](https://tsoo-math.github.io/ucl2/2021-HW-week6.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW1-sol.html)
      - [Solutions in Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week6.ipynb/%3Fflush_cache%3Dtrue)
* Week 7 (6 Oct - 12 Oct): 
  - [Exercises](https://tsoo-math.github.io/ucl2/2021-HW-week7.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW2-sol.html)
      - [Solutions in Python, including the last Q](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week7.ipynb/%3Fflush_cache%3Dtrue)
* Week 8 (13 Oct - 19 Oct):  
  - [Exercises](https://tsoo-math.github.io/ucl2/2021-HW-week8.html)
    - [Solutions in R](https://tsoo-math.github.io/ucl/QHW3-sols.html)
    - [Solutions in Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week8.ipynb/%3Fflush_cache%3Dtrue)
* Week 9 (20 Oct - 26 Oct):  
  - [Exercises](https://tsoo-math.github.io/ucl/QHW4.html)
    - [Solutions in R](https://tsoo-math.github.io/ucl/QHW4-sol.html)
    - [Solutions in Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week9.ipynb)
* Week 10 (27 Oct - 2 Nov):  
  * [ICA1 2024](https://tsoo-math.github.io/ucl5/2024-ica1-stat9-release.html)
  - [Continuous-time MC exercises](https://tsoo-math.github.io/ucl/QHW5.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW5-sols.html)
      - [Solutions in Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week10.ipynb)
  * [ICA1 2023](https://tsoo-math.github.io/ucl4/2023-ica1-stat9-release.html)      
  - [ICA1 2022](https://tsoo-math.github.io/ucl3/2022-ica1-stat9-release.html) 
    * [ICA1 2022-sols](https://tsoo-math.github.io/ucl3/2022-ica1-stat9.html)
        * [ICA1-sols 2021](https://tsoo-math.github.io/ucl2/2021-ica1-stat9.html)
* Week 11 (3 Nov - 9 Nov):  Reading break
* Week 12 (10 Nov - 16 Nov): ICA1 due
  - [Exercises](https://tsoo-math.github.io/ucl/QHW6.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW6-sols.html)
* Week 13 (17 Nov - 23 Nov):  
  - [Exercises](https://tsoo-math.github.io/ucl/QHW6.1.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW6.1-sols.html)
* Week 14 (24 Nov - 30 Nov):  
  - [Exercises](https://tsoo-math.github.io/ucl/QHW7.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW7-sols.html)
  
* Week 15 (1 Dec - 7 Dec): 
  - [Exercises](https://tsoo-math.github.io/ucl/QHW8.1.html)
    - [Solutions in R](https://tsoo-math.github.io/ucl/QHW8.1-sols.html)
  * [ICA2 2023 project ideas](https://tsoo-math.github.io/ucl4/2023-ica2-project.html)
  
* week 16 (8 Dec - 12 Dec):
  * Revisions:  
  * [ICA3 2023](https://tsoo-math.github.io/ucl4/2023-ica3-stat9-release.html)
    * [ICA3 2021](https://tsoo-math.github.io/ucl2/2021-ica3-stat9-release.html)
      * [sols](https://tsoo-math.github.io/ucl3/2021-ica3-stat9.html)
  

##  Worksheets 

*To be completed at your leisure*

* [Warm up](https://tsoo-math.github.io/ucl2/class1sol.html)

* [Gambler's ruin](https://tsoo-math.github.io/ucl/gambler-sol.html)

* [Random triangles](https://tsoo-math.github.io/ucl3/week7-2022-inclass-sols.html)

* [Reinforced random walk](https://tsoo-math.github.io/ucl3/week10-2022-inclass-sols.html)

* [Random walk on a clock](https://tsoo-math.github.io/ucl4/week8-2023-inclass-sol.html)

* [Coupling and transition matrices](https://tsoo-math.github.io/ucl2/class3-sol.html)

* [Metropolis Algorithm](https://tsoo-math.github.io/ucl4/week11-2023-inclass-sols.html)

* [Poisson process on a sphere](https://nbviewer.org/url/tsoo-math.github.io/ucl2/sphere-sol.ipynb)

* [Non-homogeneous Poisson processes](https://tsoo-math.github.io/ucl2/nonhomo-sols.html)

* [Symbolic computing](https://tsoo-math.github.io/ucl2/returntime-sol.html)

* [Return time arguments](https://tsoo-math.github.io/ucl5/week12-2024-inclass-Sols.html)

* [Excess lifetime](https://tsoo-math.github.io/ucl5/week13-2024-inclass.html)

* [Tilings](https://tsoo-math.github.io/ucl3/week14-2022-inclass-sols.html)

* [Shiny apps](https://tsoo-math.github.io/ucl5/live-stat9-2024.html)
  * [Source](https://tsoo-math.github.io/ucl/app.R)

# Other notes




<br>
<br>

 Version:  `r format(Sys.time(), '%d %B %Y')`

<br>
<br>
<br>