---
title: "Live/In-person session diary 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# General information

We may  *attempt* to live stream, the live in-person sessions.  Please note that it is UCL's expectation that students attend in-person.  The Zoom link is available [here](https://ucl.zoom.us/my/terrysoo).  Not all sessions will be recorded or streamed.  The recording links will be available on [Moodle](https://moodle.ucl.ac.uk/course/view.php?id=54044&section=0)---scroll to the bottom.


# By [UCL week](https://www.ucl.ac.uk/srs/sites/srs/files/ucl_calendar_2025_26v1.pdf)


# Week 6

* We discussed the module outline and the mechanics of the module.

* We discussed various forms of convergence and the law of large numbers.

* We ended with a question that could be tackled using simulations.

#  Week 7

* We discussed the sample of random variables

* We discussed coupling and its connection to the total variational distance


#  Week 8

* [Worksheet](https://tsoo-math.github.io/ucl6/week8-2025-inclass.html)

* We discussed Doeblin's coupling.


#  Week 9


* We continued our discussion of Doeblin's coupling
* We introduced Poisson processes as exponential inter-arrivals times and discussed their connection with uniform random variables.
* [Worksheet](https://tsoo-math.github.io/ucl6/week9-2025-inclass.html)


# Week 10

* [Poll](https://www.menti.com/alnh55uo3ngr)

* [ICA1 sample instructions](https://tsoo-math.github.io/ucl6/2025-ica1-stat9-cover.html)
  * We discussed the rules and expectations for ICA.
  * We went over last year's ICA 1.

* [ICA 1 2025](https://tsoo-math.github.io/ucl6/2025-ica1-stat9-release.html)


# Week 11 (Reading week)


# Week 12

* We discussed the feedback given in the poll
* We introduced renewal type arguments and applied them to Markov chains
* We discussed continuous-time Markov chains

#  Week 13

* We discussed renewal theory.

* We referenced the following clips:
  * [Took my feet to Oxford Street](https://youtu.be/z1rYmzQ8C9Q?si=CW40DQwby49icDow&t=44)
  * [Childhood tv show](https://youtu.be/Az6QdA_1x-k?si=lRqdxOgsVG53VN5Y&t=229)


# Week 14

* We continued our discussion of renewal theory.

* We discussed queues and Little's law.

* We introduced M/M/1 queues


#  Week 15



<br>
<br>

 Version:  `r format(Sys.time(), '%d %B %Y')`

<br>
<br>
<br>