---
title: LTTC Stochastic Processes 
author: 
date:  Fall 2021
output: html_document
---

# Mock exam

[Link](https://tsoo-math.github.io/lttc/lttc-mock.html)



#  Basics


Instructor:  Terry Soo
<br>
email:  t.soo@ucl.ac.uk
<br>
My [homepage](https://www.terrysoo.com)
<br>
Original [posting](http://www.ltcc.ac.uk/media/london-taught-course-centre/documents/Stochastic-Processes.pdf)
<br>

* 10.30-12.30; Mondays, starting November 8   
* UCL Cruciform B304 (weeks 1-4) 
* UCL Physics A1/3 (week 5)
* Zoom [link](https://ucl.zoom.us/my/terrysoo) (when available)
* Office hours, by request, most likely will be Zoom

# General links/references 

*  Related materials from UCL Stat 9 [2021](https://nbviewer.org/url/tsoo-math.github.io/ucl2/skeleton2021.ipynb)

*   Related materials from UCL Stat 9 [2020](https://tsoo-math.github.io/ucl/skeleton.html)

*  Extra reading and  [references](https://tsoo-math.github.io/lttc/references.html)

#  Schedule

*  Week1:  Introductions; Review of probability theory
    * [Recording](https://www.dropbox.com/s/ra3op7p2tuwyg77/GMT20211108-103103_Recording_1920x1080.mp4?dl=0); you may need to manually download to see the entire video.

*  Week2: Weierstrass approximation, the strong law, coupling and total variational distance.
    * [Recording](https://www.dropbox.com/s/qzzzhoa5pu4qbxl/GMT20211115-103055_Recording_1280x720.mp4?dl=0)
        *  I believe that I technically only proved the Bernstein polynomials converged pointwise, and did not argue enough that the convergence is uniform; for this, you really need to use Markov's inequality and notice that the variance is maximized at $p=\tfrac{1}{2}$; see the notes for details.  
* Week3: Markov chains and Doeblin's coupling.
  * [Recording](https://www.dropbox.com/s/6x9nzsv200bfd8q/GMT20211122-103141_Recording_1920x1080.mp4?dl=0)
* Week4: Law of large numbers for Markov chains
  * [Recording](https://www.dropbox.com/s/6oq2tv1irpghpik/GMT20211129-103153_Recording_1920x1080.mp4?dl=0)
  
* Week5: Poisson processes
  * [Recording (only first half available)](https://www.dropbox.com/s/mivsdhfu380f1id/GMT20211206-103426_Recording_1600x720.mp4?dl=0)


#  Lecture notes

* Re-introduction to probability theory (mostly review) 
  * [Sample spaces](https://tsoo-math.github.io/lttc/re-introduction.html)
  * [Random variables I](https://tsoo-math.github.io/lttc/randomrv.pdf)
  * [Random variables II](https://tsoo-math.github.io/lttc/randomrvtwo.pdf)
  * [Expectation (discrete)](https://tsoo-math.github.io/lttc/expectation-d.pdf)
  * [Expectation (continuous)](https://tsoo-math.github.io/lttc/expectation-c.pdf)

* [Probability and R](https://tsoo-math.github.io/ucl/prob-viaR.html)
* [Weierstrass approximation](https://tsoo-math.github.io/ucl2/bernstein.html)
* [The strong law of large numbers](https://tsoo-math.github.io/ucl/borel.html)
* [Coupling and total variational distance](https://tsoo-math.github.io/ucl/TV-lec.html)
* [Review of Markov chains](https://tsoo-math.github.io/ucl/reviewMC.html)
* [Coupling and the long term behaviour of Markov chains](https://tsoo-math.github.io/ucl/markov-c.html)
*  [Poisson processes](https://tsoo-math.github.io/ucl/poisson.html)
* [Continuous-time Markov chains](https://tsoo-math.github.io/ucl/continuous-timeMC.html)
*  [Renewal processes](https://tsoo-math.github.io/ucl/intro-renewal.html)

#  Other materials

* [Rolling Homework](https://tsoo-math.github.io/lttc/homeworklttc.html)
* [Worked exercises for Poisson processes](https://tsoo-math.github.io/ucl/poisson-ex.worked.html)

* [Introduction to R](https://tsoo-math.github.io/ucl/intro-R.html)
* [Introduction to Python](https://nbviewer.org/url/tsoo-math.github.io/ucl2/intro-to-python.ipynb/%3Fflush_cache%3Dtrue)
*  [Possibly related videos on YouTube (made for UCL Stat9)](https://tsoo-math.github.io/ucl2/YT.html)
  
# Endnotes

Version: `r format(Sys.time(), '%d %B %Y')`


<br>
<br>
<br>
