---
title: LTTC Stochastic Processes 
author: 
date:  Fall 2022
output: html_document
---


* [Current 2023 website](https://tsoo-math.github.io/lttc/skeleton-LTTC-2023.html)



#  Basics



Instructor:  Terry Soo
<br>
email:  t.soo@ucl.ac.uk
<br>
My [homepage](https://www.terrysoo.com)
<br>
Original [posting](http://www.ltcc.ac.uk/media/london-taught-course-centre/documents/Stochastic-Processes.pdf)
<br>

* 10.50-12.50; Mondays, 3 October - 31 October   
* De Morgan House, Russell Square

* The lectures are now completed.  I will be in contact with you in 2023 regarding the *light* assessment.  It was my pleasure to be your lecturer. 


# General links/references 

*  [Materials from 2021](https://tsoo-math.github.io/lttc/skeleton.html)

*  [Videos on YouTube](https://tsoo-math.github.io/ucl2/YT.html)


*  [Rolling homework](https://tsoo-math.github.io/lttc/homeworklttc.html)

# Classes

* Class 1: Introduction to random number generation, R, Python, and the weak law of large numbers.
  - [Intro to R](https://tsoo-math.github.io/ucl/intro-R.html)
  - [Intro to Python](https://nbviewer.org/url/tsoo-math.github.io/ucl2/intro-to-python.ipynb/%3Fflush_cache%3Dtrue)
  - [Random variables, theory and practice](https://tsoo-math.github.io/ucl/randomTP.html)
  
  - [Law of large numbers and R](https://tsoo-math.github.io/ucl/prob-viaR.html)


* Class 2: Rejection sampling, Integration,  Weierstrass approximation theorem

  - [Weierstrass](https://tsoo-math.github.io/ucl2/bernstein.html)

* Class 3: Markov chains and their convergence
  - [Introduction](https://tsoo-math.github.io/ucl/reviewMC.html)
  - [Coupling](https://tsoo-math.github.io/ucl/TV-lec.html)
    - [You always knew coupling](https://tsoo-math.github.io/ucl/coupling-rev.html)
  - [Doeblin's coupling](https://tsoo-math.github.io/ucl/markov-c.html)

* Class 4: Markov chains and Poisson point processes
  - We continued our discussion of Markov chains and their convergence
  - [Poisson processes](https://tsoo-math.github.io/ucl/poisson.html) on finite volumes
    - [Clarke's application](https://www.cambridge.org/core/journals/journal-of-the-institute-of-actuaries/article/abs/an-application-of-the-poisson-distribution/F75111847FDA534103BD4941BD96A78E)
      - [More discussion](https://rss.onlinelibrary.wiley.com/doi/pdf/10.1111/j.1740-9713.2019.01315.x)
      
* Class 5:  Poisson processes continued
  - [Continuous-time Markov chains (Optional)](https://tsoo-math.github.io/ucl/continuous-timeMC.html)

# Some code that might have been discussed in class

- [Time for the sum to exceed (Pen and Paper)](https://nbviewer.org/url/tsoo-math.github.io/ucl2/2021-hw-week6.ipynb/%3Fflush_cache%3Dtrue)

- [Rejection sampling on a disc (Section 8)](https://tsoo-math.github.io/ucl/randomTP.html)

- [Von Neumann fair bit extractor](https://nbviewer.org/url/tsoo-math.github.io/ucl2/intro-to-python.ipynb/%3Fflush_cache%3Dtrue)

- [Integration](https://nbviewer.org/url/tsoo-math.github.io/ucl2/2021-hw-week6.ipynb/%3Fflush_cache%3Dtrue)

- [Random triangles](https://tsoo-math.github.io/ucl3/week7-2022-inclass-sols.html)

- [Symbolic computing and a general two state Markov chain](https://tsoo-math.github.io/ucl3/week8-2022-inclass-sols.html)

- [Data from a MC](https://tsoo-math.github.io/ucl3/week9-2022-inclass-sols.html)

- [Shiny app for Poisson process](https://terry-soo.shinyapps.io/Poisson-disc/)
  - [Source](https://tsoo-math.github.io/ucl/app.R)

-  [Poisson process on a sphere](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/sphere-sol.ipynb)

- [Vertex reinforced random walk](https://tsoo-math.github.io/ucl3/week10-2022-inclass-sols.html)
  - [Optional materials to help understand trapping](https://tsoo-math.github.io/ucl/borel.html)

### Endnotes

Version: `r format(Sys.time(), '%d %B %Y')`


<br>
<br>
<br>
