---
title: LTTC Stochastic Processes 
author: 
date:  Fall 2023
output: html_document
---


#  Basics




Instructor:  Terry Soo
<br>
email:  t.soo@ucl.ac.uk
<br>
My [homepage](https://www.terrysoo.com)
<br>
Original [posting](http://www.ltcc.ac.uk/timetable/)
<br>

* 10.50-12.50; Mondays, 9 October - 6 November   
* De Morgan House, Russell Square
* Hardy Room (except session 2 - 16 October - that will take place at Room 14 in the 2nd floor)






# General links/references 

*  [Materials from 2022](https://tsoo-math.github.io/lttc/skeleton-LTTC-2022.html)

*  [Videos on YouTube](https://tsoo-math.github.io/ucl2/YT.html)


*  [Rolling homework](https://tsoo-math.github.io/lttc/homeworklttc.html)

# Classes

## Class one

We discussed sampling, generating random variables, and the weak law of large numbers.  we also introduced coupling.

* [Random variables theory and practice](https://tsoo-math.github.io/ucl/randomTP.html)
* [Law of large numbers and R](https://tsoo-math.github.io/ucl/prob-viaR.html)
* [Coupling](https://tsoo-math.github.io/ucl/TV-lec.html)

## Class two

We discussed Markov chains and their convergence properties

* [A simple example](https://tsoo-math.github.io/ucl4/week8-2023-inclass-sol.html)
* [Doeblin's coupling](https://tsoo-math.github.io/ucl/markov-c.html)

## Class three

We discussed coupling from the past and von Neumann's $L^2$ Ergodic Theorem

* [Coupling from the past](https://tsoo-math.github.io/ucl/coupling-from-past-lec.html)

* [The mean ergodic theorem](https://www.dropbox.com/scl/fi/6gnp5ywp2rgpirsc8yptv/lec2-von.pdf?rlkey=ltqn8y4efrr2o4ve15992azi2&dl=0)

### Endnotes

Version: `r format(Sys.time(), '%d %B %Y')`


<br>
<br>
<br>
