---
title: "Homework 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Please do the homework as posted weekly! Only the ICAs will be formally assessed and officially recorded; thus you do not need to hand in HW for the purposes of grading.



# By [UCL week](https://www.ucl.ac.uk/estates/sites/estates/files/cal_term_times_2021_2022.pdf)


* Week 6 (4 Oct - 10 Oct):  
  - [Getting started with R](https://tsoo-math.github.io/ucl2/hello-R-2001.html)
  - [Getting started with Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/hello-p.ipynb/%3Fflush_cache%3Dtrue)
  - [Exercises](https://tsoo-math.github.io/ucl2/2021-HW-week6.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW1-sol.html)
      - [Solutions in Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week6.ipynb/%3Fflush_cache%3Dtrue)
* Week 7 (11 Oct - 17 Oct): 
  - [Exercises](https://tsoo-math.github.io/ucl2/2021-HW-week7.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW2-sol.html)
      - [Solutions in Python, including the last Q](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week7.ipynb/%3Fflush_cache%3Dtrue)
* Week 8 (18 Oct - 24 Oct):  
  - [Exercises](https://tsoo-math.github.io/ucl2/2021-HW-week8.html)
    - [Solutions in R](https://tsoo-math.github.io/ucl/QHW3-sols.html)
    - [Solutions in Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week8.ipynb/%3Fflush_cache%3Dtrue)
* Week 9 (25 Oct - 31 Oct):  
  - [Exercises](https://tsoo-math.github.io/ucl/QHW4.html)
    - [Solutions in R](https://tsoo-math.github.io/ucl/QHW4-sol.html)
    - [Solutions in Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week9.ipynb)
* Week 10 (1 Nov - 7 Nov):   
  - [ICA1](https://tsoo-math.github.io/ucl2/2021-ica1-stat9-release.html) assigned
      * [ICA1-sols](https://tsoo-math.github.io/ucl2/2021-ica1-stat9.html)
  - [Continuous-time MC exercises](https://tsoo-math.github.io/ucl/QHW5.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW5-sols.html)
      - [Solutions in Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/2021-hw-week10.ipynb)
* Week 11 (8 Nov - 14 Nov):  Reading break
* Week 12 (15 Nov - 21 Nov): ICA1 due
  - [Exercises](https://tsoo-math.github.io/ucl/QHW6.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW6-sols.html)
* Week 13 (22 Nov - 28 Nov):  
  - [Exercises](https://tsoo-math.github.io/ucl/QHW6.1.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW6.1-sols.html)
* Week 14 (29 Nov - 5 Dec):  
  - [Exercises](https://tsoo-math.github.io/ucl/QHW7.html)
      - [Solutions in R](https://tsoo-math.github.io/ucl/QHW7-sols.html)
  
* Week 15 (6 Dec - 12 Dec): 
  - [Exercises](https://tsoo-math.github.io/ucl/QHW8.1.html)
    - [Solutions in R](https://tsoo-math.github.io/ucl/QHW8.1-sols.html)
  * [ICA2 released](https://tsoo-math.github.io/ucl2/ICAproject-ideas-2021.html)
  
* week 16 (13 Dec - 19 Dec):
  * Revisions:  see last ICA1 and 3 from 2020
  * [ICA3 released](https://tsoo-math.github.io/ucl2/2021-ica3-stat9-release.html)
  

* week 24: (7 Feb - 13 Feb;  2022):  [ICA3](https://tsoo-math.github.io/ucl2/2021-ica3-stat9-release.html) due
* week 27: (28 Feb 6 Mar; 2027):  [ICA2](https://tsoo-math.github.io/ucl2/ICAproject-ideas-2021.html) due

# Other notes

* [Homework from 2020](https://tsoo-math.github.io/ucl/homework.html) 

* [ICA1 from 2020](https://tsoo-math.github.io/ucl/ica-stat9.html)

*  [ICA 3 from 2020](https://tsoo-math.github.io/ucl/ica3-stat9-sols.html)



* First term Monday (27 September 2021 -- Friday 17 December 2021)



<br>
<br>

 Version:  `r format(Sys.time(), '%d %B %Y')`

<br>
<br>
<br>