---
title: "ICA2 possible projects"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
 
* This ICA is worth 40 percent of your grade for this module.
*  This ICA is due UCL Week 27,  3 March 2022, 13:00 London Time.
*  This ICA is to be completed in a group of 3-4; each member of the group will receive the same grade.
*  Your groups must be disjoint from that of ICA3.
* A grading scheme is available [here](https://tsoo-math.github.io/ucl/ICA-gradingform.html)
* The ICA must be completed in R/Python and typeset using Markdown with Latex code, just like the way our module content is generated.
* Please hand in the html (or pdf file) and the Rmd/Jupyter notebook source files.
* As usual, part of the grading will depend on the clarity and presentation of your solutions.
*  You are to do this assignment, within your groups, without any help from others.
*  You are allowed to use any materials and code that was presented so far.
*  Do not use any fancy code or packages imported from elsewhere.



#  Plagiarism and collusion

Please familarize yourself with [the following excerpt on plagiarism and collusion from the student handbook ](https://tsoo-math.github.io/ucl/Plagiarism-Collusion.pdf)


By ticking the submission declaration box in Moodle you are agreeing to the following declaration:

<br>

**Declaration:** I am aware of the UCL Statistical Science Department's regulations on plagiarism for assessed coursework. I have read the guidelines in the student handbook and understand what constitutes plagiarism. I hereby affirm that the work I am submitting for this in-course assessment is entirely my own.



# Anonymous Marking 

Please do **not** write your names anywhere on the submission. Please include only your **student numbers** as a proxy identifier.



# ICA project ideas

The following are some suggestions, but you are free to choose your own projects and directions.  If you choose a project that is not listed here, I would like to have a chat with you and your group first to make sure it is suitable.  It is possible that more than one group chooses the same or similar project.  It is important that each group works on their own; in particular, two groups working on the same or similar project should not be helping each other on the project.  Please feel free to discuss with me for more details and directions regarding the following suggestions.



*  There is a text (from a prison) that was coded using a Ceasar cipher; this was decoded using just pairwise probabilities, Markov chains.  One project I had in mind was to decode this text or encode/decode other suitably available texts, and also see if using a longer memory makes a difference. [background](https://www.ams.org/journals/bull/2009-46-02/S0273-0979-08-01238-X/) 



*  	Various projects on card shuffling.  One would explore various shuffles and discuss using theory and simulation.  For example, see these papers and the references within:  [overhand shuffle](https://arxiv.org/pdf/math/0501401.pdf) [Shuffling cards and stopping times (use UCL VPN for link)](https://www.jstor.org/stable/2323590?origin=crossref&seq=1)
[How many times do I have to shuffle this deck](http://www.ams.org/publicoutreach/feature-column/fcarc-shuffle)

* 	Queuing:  central versus individual queues:  does it make sense that bank use centralized queues and supermarkets individual queues?

*  How to manage line-ups? Hospitals and other institutions   put priority based on need, but you can't make someone with a broken ankle wait forever?


* 	Various models in statistical physics: eg: Discuss the Ising model, sample it using MCMC.  For example, this [paper](https://arxiv.org/abs/1012.3944) considers exact sampling.


* 	Applications of MCMC to Bayesian statistics:  discuss the basic Bayesian framework,  and how MCMC is applied, supporting the examples with code.  

*  	Random number generation: discuss the theory and practice of random number generation. 

* 	Discuss Quasi-Monte Carlo methods and illustrate theory with examples and simulations.  There is an introduction [here](http://websrv.cs.fsu.edu/~mascagni/Caflisch_1998_Acta_Numerica.pdf)
 

*  Hidden Markov chains:  Often the observation we see do not correspond to a Markov chain, but in the background a Markov chain is pulling the string.   


* 	Write a report on a research paper, working through some of the theory and illustrating relevant examples via coding/simulation.


* 	Write a report on an more advanced topic that was not covered in the module, and illustrate the relevant example via coding/simulation:  eg solutions of PDE via probability  theory, random walk and electrical networks.








<br>
<br>

Version: `r format(Sys.time(), '%d %B %Y')`



<br>
<br>
<br>
