---
title: "Live/In-person session diary 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# General information

We will *attempt* to live stream, the live in-person sessions.  Please note that it is UCL's expectation that students attend in-person.  The Zoom link is available [here](https://ucl.zoom.us/my/terrysoo).  Not all sessions will be recorded.


# By [UCL week](https://www.ucl.ac.uk/estates/sites/estates/files/cal_term_times_2021_2022.pdf)

* Week 6 (4 Oct - 10 Oct):  
  - Introductions, first meeting.
  - [Exercise sheet](https://tsoo-math.github.io/ucl2/2021-week6.html)
    - [Solutions](https://tsoo-math.github.io/ucl2/class1sol.html)
  - [Introduction to Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/intro-to-python.ipynb/%3Fflush_cache%3Dtrue)
  - This session was recorded, and will be available on Moodle, but not YouTube.
* Week 7 (11 Oct - 17 Oct): 
  - We discussed the some questions/material from Week 6; in particular, why histograms approximate the true density of a random sample.  We went into groups to discuss two exercise sheets.
  - [Gambler's ruin with R](https://tsoo-math.github.io/ucl/gambler.html)
    - [Gambler's solutions](https://tsoo-math.github.io/ucl/gambler-sol.html)
  - [Estimators with Python](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/ergodic-biased.ipynb/%3Fflush_cache%3Dtrue)
    -  [Estimators' solutions](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/ergodic-biased-sol.ipynb)
  - This session was not recorded.
* Week 8 (18 Oct - 24 Oct):  
  -  We discussed material from last week; in particular, coupling and total variational distance.
  - [Exercise sheet](https://tsoo-math.github.io/ucl2/class3.html)
    - [Partial solutions](https://tsoo-math.github.io/ucl2/class3-sol.html)
  - This session was recorded, and available only on Moodle.
* Week 9 (25 Oct - 31 Oct):  
  - We discussed material from last week; in particular coupling from the past.  We also discussed the mechanics, logistics, and expectations for ICA1. 
  - [Python inside R](https://tsoo-math.github.io/ucl2/class4.1.html)
  - [Exercise sheet](https://tsoo-math.github.io/ucl2/class4.html)
      - [Partial Solutions](https://tsoo-math.github.io/ucl2/class4-sol.html)
  - This session was recorded, and only available on Moodle.  
* Week 10 (1 Nov - 7 Nov):   
  - [Poisson process on a sphere](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/sphere.ipynb)
      - [Solutions](https://nbviewer.jupyter.org/url/tsoo-math.github.io/ucl2/sphere-sol.ipynb)
  - [Non-homogeneous Poisson process](https://tsoo-math.github.io/ucl2/nonhomo.html)
      - [Solutions](https://tsoo-math.github.io/ucl2/nonhomo-sols.html)
  - [ICA1](https://tsoo-math.github.io/ucl2/2021-ica1-stat9-release.html) assigned
  - This meeting was recorded and will be available in Moodle.
* Week 11 (8 Nov - 14 Nov):  Reading break
* Week 12 (15 Nov - 21 Nov): 
  - We discussed some previous homework exercises, and background for ICA2. 
  - [Weierstrass approximation theorem](https://tsoo-math.github.io/ucl2/bernstein.html)
  - This session was recorded, and will be available on Moodle, only.
* Week 13 (22 Nov - 28 Nov):  
  - [Exercise sheet](https://tsoo-math.github.io/ucl2/returntime.html)
* Week 14 (29 Nov - 5 Dec):  
  
* Week 15 (6 Dec - 12 Dec): ICA2 and ICA3 assigned
  
* week 16 (13 Dec - 19 Dec):
  

* week 23: (31 Jan - 6 Feb;  2022):  ICA3 due
* week 27: (28 Feb 6 Mar; 2027):  ICA2 due

# Other notes

* First term Monday (27 September 2021 -- Friday 17 December 2021)



<br>
<br>

 Version:  `r format(Sys.time(), '%d %B %Y')`

<br>
<br>
<br>